### ISSUE TITLE
Modules don't work as intended.

### ISSUE THREAD

**Issue by rathodkanishk** [ManneN1/GladiusEx-WotLK#1]
I tried using this recently, but it seems that many of the modules don't function as intended.

The DR Tracker doesn't show any DRs even though I've enabled it.
The announcements (enemy team spec, drinking, ressing, low health) don't work.

Is there some way to fix these?

I absolutely love the fact that you've backported this for wotlk, and honestly my friends and I really want to use this. 
If there's any help we can provide to help get this to work, we would love to help out.

**Comment by ManneN1** [comment]
Is there a WotLK private server realm with 1v1 wargames where I can test things?

Alternatively, is there a WotLK private server that doesnt mind me essentially wintrading 6x accounts at low MMR to try to fix the issues?

The main problem with maintaining this is there's no real environment where all of this can be tested well.

**Comment by rathodkanishk** [comment]
Hey ManneN, thanks for responding. 

I currently play at https://www.winter-wow.com/ and we have a low population. 
I can personally help you test this addon out to get it fixed - because this is honestly the HOLY GRAIL of pvp addons imo.

The population is quite low so that would mean that we could just queue into each other as many times as we like to get the bugs fixed. You can add me on discord Grimzley#8156 and we could chat more about this there.

**Comment by rathodkanishk** [comment]
Hey ManneN, any update?

**Comment by ManneN1** [comment]
Well, I need to play against myself so I can test at my own pace - it doesn't really work when playing with others.

Until such a realm with 1v1 wargame and no rules against playing multiple accounts at once comes along Ill have a hard time fixing it.

**Comment by rathodkanishk** [comment]
You can test it for yourself on our server. 

There aren't any rules against multi-boxing, and you can queue skirmish into yourself (people rarely queue skirmish). 
Multi-boxing is quite common on our server, and as long as you're not queuing for rated games (wintrading) I don't think it will be an issue. If you wish, I can contact the mods to assist you with getting max level characters for your testing.

**Comment by ManneN1** [comment]
I have now found a realm that hopefully works for what I need. I will try to see if I can fix the issues you have reported.

**Comment by ManneN1** [comment]
Should be fixed in https://github.com/ManneN1/GladiusExBackport-WotLK/commit/445087b76e126d7901f993e5b73d270588a21ddd

Please re-open or otherwise contact me if the issues persist.
