### ISSUE TITLE
EMHF doesn't trigger pvp trinket icon cooldown

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#10]
I cannot see the PVP trinket cooldown for humans anymore with only 1 icon. I have to make that cooldown group show multiple icons (EMHF and WOTF as well as PVP Trinket) and it occupies a lot of space now). WOTF may have a problem too, not sure, am assuming for now it does.

**Comment by ManneN1** [comment]
Fixed in d18840f45a0b99efb203eed0ee01a8986d2cdd67.
