### ISSUE TITLE
Class Icon Show Trinket and Trinket CD

### ISSUE THREAD

**Issue by wowluanoob** [ManneN1/GladiusEx-WotLK#16]
Is it possible to add an option to display trinket availability instead of spec, class and portrait?

**Comment by wowluanoob** [comment]
i found an alternative

**Comment by ManneN1** [comment]
For others looking: It's entirely possible to hide the classicon (portrait) module entirely and moving the trinket icon to where it would've been. For an example of how to configure the trinket icon to end up on the left / right side (depending on if it's for arena or party units) just look at the default settings for the party and arena trinket cooldown groups respectively.
