### ISSUE TITLE
Error on join arena

### ISSUE THREAD

**Issue by wowluanoob** [ManneN1/GladiusEx-WotLK#18]
Message: Interface\AddOns\GladiusEx\GladiusEx.lua:522: bad argument #2 to 'strsplit' (string expected, got nil)
Time: 07/19/24 15:29:37
Count: 1
Stack: (tail call): ?
[C]: in function `strsplit'
Interface\AddOns\GladiusEx\GladiusEx.lua:522: in function `GetAlwaysUpFrameForPlayers'
Interface\AddOns\GladiusEx\GladiusEx.lua:472: in function `GetArenaSize'
Interface\AddOns\GladiusEx\GladiusEx.lua:503: in function `CheckArenaSize'
Interface\AddOns\GladiusEx\GladiusEx.lua:657: in function `ShowFrames'
Interface\AddOns\GladiusEx\GladiusEx.lua:707: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: No locals to dump

I get this on join arena is this an ElvUI problem or GladiusEX?

**Comment by wowluanoob** [comment]
when it shows up it seems that DR icons are not working

**Comment by ManneN1** [comment]
Is ElvUI doing something about the "3 Players Remaining" text at the top of the screen? Such as removing/hiding/changing the text of it?

**Comment by wowluanoob** [comment]
no afaik. its still the default yellow text that it is.

EDIT: installed new commit and will test.

**Comment by wowluanoob** [comment]
seems fixed
