### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by wowluanoob** [ManneN1/GladiusEx-WotLK#19]
I like the ability to track other peoples DRs and CDs with the DR Tracker/Cooldowns modules. One problem only - that the swipe feature is very hard to see and the amount of DR (1/2,1/4...) max size is also not big enough. Yes there is on cooldown alpha for the cds, but you still are required to do radians maths and other trigonometry to know when CD or DR will end. If its possible to add a timer feature something like this it would be really cool.
![image](https://github.com/user-attachments/assets/137f3600-c270-4c02-b140-a7810b79cdcb)

Its far easier to see and know exactly when a DR/CD will be online. It could be if < 1 minute then show in seconds or other way configurable.

**Comment by wowluanoob** [comment]
Im trying to do this by adding a testtext FontString to the topleft inside of the DRTracker Icon,
```
--test text
    tracked.testtext:SetFont(LSM:Fetch(LSM.MediaType.FONT, "2002"), self.db[unit].drFontSize, "OUTLINE")
    tracked.testtext:ClearAllPoints()
    tracked.testtext:SetPoint("TOPLEFT", tracked, 2, 0)
    tracked.testtext:SetDrawLayer("OVERLAY")
    tracked.testtext:SetJustifyH("LEFT")
    tracked.testtext:Show()
    --tracked.testtext:SetText("Test")
```
then set the text of it in the onUpdate function in function DRFaded() but its not working. I cant follow the logic of `applied` at ln257 it seems that this refers to the cooldown finishing and updating the sort icons. but also at ln247 you have if applied then cooldown:hide() which doesnt make sense since we want to set the cooldown when we apply a debuff and we increase the diminishing returns text

I added the fontstring in CreateIcon() (tested it by setting text to 'test')
Then in DRFaded() at the `elseif applied and useApplied` (ln256) i added this piece of code but its not displaying at all.
```
tracked:SetScript("OnUpdate", function(f, elapsed)
            --my test timer
            local testtexttimer = 0
            testtexttimer = testtexttimer + elapsed
            local test_time_left = time_left
            if testtexttimer >= 1 then
                f.testtext:SetText(test_time_left)
                testtexttimer = 0
                test_time_left = test_time_left - 1
                if test_time_left == 0 then
                    f.testtext:Hide()
                    --f.testtext:SetText("Test")
                    test_time_left = time_left
                end
            end
        end)
```
This is a simple timer that increments with elapsed. if timer is >= 1 (1 second has passed) then we set the text to a copy of time_left (diminishing returns reset time), we reset the timer to 0 and we substract 1 second from the copy of time_left so we can display it next time, also if test_time_left is 0 then we have no DR so we hide the text.

Did i place my timer in the wrong spot or am i doing something wrong?
Edit even tried putting my timer right after ln242 tracked.cooldown:Show() and its not working

**Comment by wowluanoob** [comment]
You could've just said to use OmniCC...
Also your table in interrupts that was global before my PR was interfering with GlobalString INTERRUPTS which is used by CombatLog check https://old.wow.tools/dbc/?dbc=globalstrings&build=3.4.1.47720#page=1&search=INTERRUPTS
![image](https://github.com/user-attachments/assets/2587c309-dab5-4be5-959d-9f1aba32c9df)

![image](https://github.com/user-attachments/assets/fa7d90ba-ede2-49aa-9bfe-d6410e99d504)
You saying it has nothing to do with this addon is just invalid and as i said it started happening after installing GladiusEx so its from it

**Comment by ManneN1** [comment]
Good catch. Unforunately 99% of people who claim "your addon is breaking CombatLog" just don't know what they're talking about, and given your name my confidence was not high.

Edit: I see now that what you've referenced is from the WotLK Classic client. So again, I don't know that you're correct.
Edit2: It seems the GlobalString also exists in WotLK 3.3.5:
https://github.com/wowgaming/3.3.5-interface-files/blob/main/GlobalStrings.lua#L4283C1-L4283C27
