### ISSUE TITLE
Trinket module disappeared?

### ISSUE THREAD

**Issue by rathodkanishk** [ManneN1/GladiusEx-WotLK#2]
Hello Mannen, 

I can't see the trinket module anymore (the enemy trinket indicator). Is that intended?

The trinket module is pretty crucial in PVP as you may know.

**Comment by rathodkanishk** [comment]
Any update?

**Comment by ManneN1** [comment]
Hello,

I had covid so as a result I was not able to work on this.

However, as you can see in the readme and main page of this repo: "Furthermore, the cooldowns module has been permanently removed (until someone backports LibCooldownTracker to 3.3.5)". This implies that trinkets are not tracked, as they are part of the cooldowns module. I am highly surprised you were ever able to see a "Trinket" module as that has never been part of GladiusEx-WotLK.

Lastly, I did push a commit just now (https://github.com/ManneN1/GladiusExBackport-WotLK/commit/8c9e662e901fe4e22a4f3766e37aa22de59916cb) which adds alpha support for the LibCooldownTracker library and the Cooldowns module. Feel free to use (at your own risk). Feel free to report any bugs with the commit.
