### ISSUE TITLE
Lua error on character title change

### ISSUE THREAD

**Issue by wowluanoob** [ManneN1/GladiusEx-WotLK#22]
While in BG i change my char title and this error pops up

Message: Interface\AddOns\GladiusEx\GladiusEx.lua:523: bad argument #2 to 'strsplit' (string expected, got nil)
Time: 08/23/24 10:42:37
Count: 2
Stack: (tail call): ?
[C]: in function `strsplit'
Interface\AddOns\GladiusEx\GladiusEx.lua:523: in function `GetAlwaysUpFrameForPlayers'
Interface\AddOns\GladiusEx\GladiusEx.lua:472: in function `GetArenaSize'
Interface\AddOns\GladiusEx\GladiusEx.lua:503: in function `CheckArenaSize'
Interface\AddOns\GladiusEx\GladiusEx.lua:922: in function `?'
...Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: No locals to dump

**Comment by wowluanoob** [comment]
i suggest adding 
if select(2, IsInInstance()) ~= "arena" then return end
to that function

**Comment by ManneN1** [comment]
Fixed in https://github.com/ManneN1/GladiusEx-WotLK/commit/a72a724dbda80afa4cba47701a29cef357d7b5c8.

Utilizing IsActiveBattlefieldArena() is slightly more efficient than select and the string comparison.

Thanks for the report. 👍
