### ISSUE TITLE
Cooldown module missing a lot. 

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#3]
Hi, the cooldown module is missing a lot of important cooldowns, and it also seems to have inappropriate cooldowns from other patches.

**Comment by Akcentx** [comment]
> Привет, в модуле перезарядки отсутствует много важных перезарядок, а также, кажется, есть неподходящие перезарядки из других патчей.

Каких именно?

**Comment by ManneN1** [comment]
Yes, the Cooldown module is in alpha. It is stated on the main page.

If you know which spells are incorrect I can update it but since I dont play WotLK and even if I did I dont use the cooldown module (beyond trinket CD) I can't do it myself.

**Comment by SamiRayR** [comment]
Thank you for replying. I will draw up a list of spells and get back to you soon.

**Comment by ManneN1** [comment]
PS: Anyone who reads this can write missing / incorrect abilities here and I will update the AddOn with them.

**Comment by MaelKoT** [comment]
there is my cooldownlist for last wotlk Gladius v1.2.0 https://pastebin.com/QMzL2ums
i know that there is complitely different way to set spell cooldowns, but maybe this can be helpful

(i dont play wotlk anymore too, but maybe someone can just compare some spellid's and look if there is wrong cd numbers for them:))

**Comment by ManneN1** [comment]
Just a reminder to everyone reading this: If you happen to have a list which is essentially complete, separated per class, and not in russian feel free to drop it here.

**Comment by 3majed** [comment]
Hope this help
- CD list
https://github.com/Cortes-Jeremy/Gladius/blob/master/Gladius/cooldownlist.lua
- Aura list
https://github.com/Cortes-Jeremy/Gladius/blob/master/Gladius/auralist.lua
- Spec list
https://github.com/Cortes-Jeremy/Gladius/blob/master/Gladius/speclist.lua
- DR list
https://github.com/Cortes-Jeremy/Gladius/blob/master/Gladius/drlist.lua

**Comment by seternate** [comment]
Hi, would like to help out here - since I am trying to use this. Any idea how I can fix this?
Errors for this problem coming in via Chat e.g.:
LibCooldownTracker-1.0: bad spellid for PRIEST: 108920

One example is missing "Dispersion" for Shadow Priest.

**Comment by ManneN1** [comment]
Fixed by [e6bf103613266487144b0800cabd961bf2fce309](https://github.com/ManneN1/GladiusEx-WotLK/commit/e6bf103613266487144b0800cabd961bf2fce309). Might still need minor tailoring to get all abilities correct (CDs might be slightly off, a few abilities could be missing etc).

**Comment by ManneN1** [comment]
Fixed by [e6bf103613266487144b0800cabd961bf2fce309](https://github.com/ManneN1/GladiusEx-WotLK/commit/e6bf103613266487144b0800cabd961bf2fce309). Might still need minor tailoring to get all abilities correct (CDs might be slightly off, a few abilities could be missing etc).
