### ISSUE TITLE
Conflicts with Skada's Interrupts module

### ISSUE THREAD

**Issue by nogoodlife** [ManneN1/GladiusEx-WotLK#4]
Please rename the Interrupts module to InterruptsEx or smtng to avoid conflicts with Skada (https://github.com/bkader/Skada-WoTLK)

**Comment by ManneN1** [comment]
This should be resolved with https://github.com/ManneN1/GladiusExBackport-WotLK/commit/82c163528ea6d1eb029423f8ad2f1a4bb18c618f although I want to point out that this is not GladiusEx's fault, and that the author of Skada may as well change the name of his frames instead.
