### ISSUE TITLE
UI is not visible

### ISSUE THREAD

**Issue by seternate** [ManneN1/GladiusEx-WotLK#6]
Hello, after your updates to the Cooldown module the UI of GladiusEx is not visible anymore, neither within "Interface" nor with "/gladiusex" / "gladiusex ui".

Can not see what was done in that regards to break the UI.
Thanks for your help.

**Comment by ManneN1** [comment]
Should be fixed in https://github.com/ManneN1/GladiusEx-WotLK/commit/0ca0ca368c01b6086c4be353799f42b6c62d4cae.
