### ISSUE TITLE
Priest cooldowns now missing

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#8]
In the newest update, priest cooldowns are missing

**Comment by ManneN1** [comment]
I am not able to reproduce:

Before detecting spec (enemy):
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/f6d0b687-1dfd-48f4-9cf8-fcfdf16b5b61)

After detecting spec (enemy):
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/41e3579f-4346-48b2-8102-e571b24cb532)

Before detecting spec (friendly):
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/d1bb0b67-51bc-4a77-810b-41b5f065c063)

After detecting spec (friendly):
![image](https://github.com/ManneN1/GladiusEx-WotLK/assets/16864855/0b7d09c9-bdb3-41bb-ad03-eb3c6a87f1c2)

Are you able to clarify steps to reproduce?

**Comment by ManneN1** [comment]
Should be fixed in https://github.com/ManneN1/GladiusEx-WotLK/commit/1407b4909e432c51dd62f88beaf19bd4a83a21e3.
