### ISSUE TITLE
Roar of Sacrifice does not appear in Checkbox options

### ISSUE THREAD

**Issue by SamiRayR** [ManneN1/GladiusEx-WotLK#9]
For me at least Roar of Sacrifice is missing:

![Screen Shot 2023-10-28 at 6 40 21 PM](https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/0dc7c0b1-f66b-4859-aa2b-ad4aee7818f5)

I see it in the lua files though:

![Screen Shot 2023-10-28 at 6 46 03 PM](https://github.com/ManneN1/GladiusEx-WotLK/assets/96414645/40db80fc-9feb-4154-962a-6609dfea7aee)

**Comment by ManneN1** [comment]
Fixed in a261b15d13fb39039cde1196ccdb9b0950c2135a.
